dataset_path: /data/disk1/share/luriz/datasets/SemanticPOSS/dataset/

folder_name:
  input: velodyne
  label: labels

split_sequence: # sequence numbers
  train:
    - '00'
    - '01'
    - '02'
    - '04'
    - '05'
  valid:
    - '03'

learning_map:
  0: -1 # unlabeled
  1: -1 # unlabeled -------------------------------mapped
  2: -1 # unlabeled -------------------------------mapped
  3: -1 # unlabeled -------------------------------mapped
  4: 0 # 1 person
  5: 0 # 2+ person --------------------------------mapped
  6: 1 # rider
  7: 2 # car
  8: 3 # trunk
  9: 4 # plants
  10: 5 # traffic sign 1 
  11: 5 # traffic sign 2 --------------------------mapped
  12: 5 # traffic sign 3 --------------------------mapped
  13: 6 # pole
  14: 7 # trashcan
  15: 8 # building
  16: 9 # cone/stone
  17: 10 # fence
  18: -1 # unlabeled -------------------------------mapped
  19: -1 # unlabeled -------------------------------mapped
  20: -1 # unlabeled -------------------------------mapped
  21: 11 # bike
  22: 12 # other-ground

learning_map_inv: # inverse of previous map
  -1: 0     # "unlabeled", and others ignored
  0: 4     # "person"
  1: 6     # "rider"
  2: 7     # "car"
  3: 8     # "trunk"
  4: 9     # "plants"
  5: 10     # "traffic-sign"
  6: 13     # "pole"
  7: 14     # "trashcan"
  8: 15     # "building"
  9: 16     # "cone/stone"
  10: 17    # "fence"
  11: 21    # "bike"
  12: 22    # "other-ground"

color_map: # bgr
  0: [128, 128, 128] # unlabeled
  1: [0, 0, 0] # unlabeled
  2: [0, 0, 0] # unlabeled
  3: [0, 0, 0] # unlabeled
  4: [255, 30, 30] # 1 person
  5: [255, 30, 30] # 2+ person
  6: [255, 40, 200] # rider
  7: [100, 150, 245] # car
  8: [135,60,0] # trunk
  9: [0, 175, 0] # plants
  10: [255, 0, 0] # traffic sign 1 # standing sign
  11: [255, 0, 0] # traffic sign 2 # hanging sign
  12: [255, 0, 0] # traffic sign 3 # high/big hanging sign
  13: [255, 240, 150] # pole
  14: [125, 255, 0] # trashcan
  15: [255, 200, 0] # building
  16: [50, 255, 255] # cone/stone
  17: [255, 120, 50] # fence
  18: [0, 0, 0] # unlabeled
  19: [0, 0, 0] # unlabeled
  20: [0, 0, 0] # unlabeled
  21: [100, 230, 245] # bike
  22: [0, 0, 0] # other-ground

labels: 
  0: "unlabeled"
  4: "person"
  5: "2+ person"
  6: "rider"
  7: "car"
  8: "trunk"
  9: "plants"
  10: "traffic sign" # standing sign
  11: "traffic sign 2" # hanging sign
  12: "traffic sign 3" # high/big hanging sign
  13: "pole"
  14: "trashcan"
  15: "building"
  16: "cone-stone"
  17: "fence"
  21: "bike"
  22: "other-ground"

content: # as a ratio with the total number of points
  0: 2.14244059e-02
  1: 2.59110680e-08
  2: 0.0
  3: 0.0
  4: 1.45552885e-02
  5: 2.97170930e-03
  6: 4.27795878e-03
  7: 7.47442017e-02
  8: 1.19028088e-02
  9: 3.64772113e-01
  10: 2.93810782e-03
  11: 1.22949054e-03
  12: 1.45168831e-03
  13: 4.73977693e-03
  14: 8.20411782e-04
  15: 2.22458412e-01
  16: 9.10416468e-04
  17: 1.53973464e-02
  18: 7.59448221e-04
  19: 3.80011723e-05
  20: 3.34610350e-04
  21: 5.48716718e-02
  22: 1.99402106e-01